[package]
name = "eer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
image = "0.25.5"
ndarray = "0.16.1"
quick-xml = "0.37.2"
serde = "1.0.218"
serde_derive = "1.0.218"
serde_json = "1.0.139"
tiff = "0.9.1"
